<?php
$con = mysqli_connect("localhost","root","","task");
$success = false;
$dt1 = $_POST['date1'];
$income1 = $_POST['income1'];
echo $income1;
$expence1 = $_POST['expence1'];
$income2 = $_POST['income2'];
$expence2 = $_POST['expence2'];
$dt2 = $_POST['date2'];
$income3 = $_POST['income3'];
$expence3 = $_POST['expence3'];
$dt3 = $_POST['date3'];
$income4 = $_POST['income4'];
$expence4 = $_POST['expence4'];
$dt4 = $_POST['date4'];
$income5 = $_POST['income5'];
$expence5 = $_POST['expence5'];
$dt5 = $_POST['date5'];
$income6 = $_POST['income6'];
$expence6 = $_POST['expence6'];
$dt6 = $_POST['date6'];
$income7 = $_POST['income7'];
$expence7 = $_POST['expence7'];
$dt7 = $_POST['date7'];
$sql1 = "INSERT INTO `reports` (`income`, `expence`, `dt`) VALUES ('$income1', '$expence1', '$dt1')";
$sql2 = "INSERT INTO `reports` (`income`, `expence`, `dt`) VALUES ('$income2', '$expence2', '$dt2')";
$sql3 = "INSERT INTO `reports` (`income`, `expence`, `dt`) VALUES ('$income3', '$expence3', '$dt3')";
$sql4 = "INSERT INTO `reports` (`income`, `expence`, `dt`) VALUES ('$income4', '$expence4', '$dt4')";
$sql5 = "INSERT INTO `reports` (`income`, `expence`, `dt`) VALUES ('$income5', '$expence5', '$dt5')";
$sql6 = "INSERT INTO `reports` (`income`, `expence`, `dt`) VALUES ('$income6', '$expence6', '$dt6')";
$sql7 = "INSERT INTO `reports` (`income`, `expence`, `dt`) VALUES ('$income7', '$expence7', '$dt7')";
$result1 = mysqli_query($con,$sql1);
$result2 = mysqli_query($con,$sql2);
$result3 = mysqli_query($con,$sql3);
$result4 = mysqli_query($con,$sql4);
$result5 = mysqli_query($con,$sql5);
$result6 = mysqli_query($con,$sql6);
$result7 = mysqli_query($con,$sql7);
mysqli_close($con);
?>